<?php
namespace Database\Seeders;

use App\Models\Taxonomia;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TaxonomiaSeeder extends Seeder
{
    public function run(): void
    {
        $taxonomiasFlora = [
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Pinopsida',
                'orden'         => 'Pinales',
                'familia'       => 'Taxaceae',
                'genero'        => 'Taxus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fagales',
                'familia'       => 'Fagaceae',
                'genero'        => 'Quercus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fagales',
                'familia'       => 'Fagaceae',
                'genero'        => 'Fagus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fagales',
                'familia'       => 'Fagaceae',
                'genero'        => 'Castanea',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fagales',
                'familia'       => 'Betulaceae',
                'genero'        => 'Betula',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Sapindales',
                'familia'       => 'Aceraceae',
                'genero'        => 'Acer',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fagales',
                'familia'       => 'Betulaceae',
                'genero'        => 'Corylus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Lamiales',
                'familia'       => 'Oleaceae',
                'genero'        => 'Fraxinus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Salicales',
                'familia'       => 'Salicaceae',
                'genero'        => 'Salix',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fabales',
                'familia'       => 'Fabaceae',
                'genero'        => 'Genista',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fabales',
                'familia'       => 'Fabaceae',
                'genero'        => 'Ulex',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Ericales',
                'familia'       => 'Ericaceae',
                'genero'        => 'Erica',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Aquifoliales',
                'familia'       => 'Aquifoliaceae',
                'genero'        => 'Ilex',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Rosales',
                'familia'       => 'Rosaceae',
                'genero'        => 'Sorbus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Rosales',
                'familia'       => 'Rosaceae',
                'genero'        => 'Prunus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Liliopsida',
                'orden'         => 'Asparagales',
                'familia'       => 'Amaryllidaceae',
                'genero'        => 'Narcissus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Polypodiopsida',
                'orden'         => 'Osmundales',
                'familia'       => 'Osmundaceae',
                'genero'        => 'Osmunda',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Fagales',
                'familia'       => 'Betulaceae',
                'genero'        => 'Alnus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Bryophyta',
                'clase'         => 'Sphagnopsida',
                'orden'         => 'Sphagnales',
                'familia'       => 'Sphagnaceae',
                'genero'        => 'Sphagnum',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Lamiales',
                'familia'       => 'Lamiaceae',
                'genero'        => 'Thymus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Rosales',
                'familia'       => 'Rosaceae',
                'genero'        => 'Rubus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Liliopsida',
                'orden'         => 'Poales',
                'familia'       => 'Juncaceae',
                'genero'        => 'Juncus',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Polypodiopsida',
                'orden'         => 'Polypodiales',
                'familia'       => 'Dryopteridaceae',
                'genero'        => 'Dryopteris',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Saxifragales',
                'familia'       => 'Grossulariaceae',
                'genero'        => 'Ribes',
            ],
            [
                'reino'         => 'Plantae',
                'filo_division' => 'Tracheophyta',
                'clase'         => 'Magnoliopsida',
                'orden'         => 'Gentianales',
                'familia'       => 'Gentianaceae',
                'genero'        => 'Gentiana',
            ],
        ];

        $taxonomiasFauna = [
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Carnivora',
                'familia'       => 'Ursidae',
                'genero'        => 'Ursus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Artiodactyla',
                'familia'       => 'Cervidae',
                'genero'        => 'Capreolus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Carnivora',
                'familia'       => 'Canidae',
                'genero'        => 'Canis',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Carnivora',
                'familia'       => 'Mustelidae',
                'genero'        => 'Lutra',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Carnivora',
                'familia'       => 'Mustelidae',
                'genero'        => 'Mustela',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Artiodactyla',
                'familia'       => 'Bovidae',
                'genero'        => 'Rupicapra',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Aves',
                'orden'         => 'Galliformes',
                'familia'       => 'Phasianidae',
                'genero'        => 'Tetrao',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Aves',
                'orden'         => 'Falconiformes',
                'familia'       => 'Accipitridae',
                'genero'        => 'Aquila',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Aves',
                'orden'         => 'Falconiformes',
                'familia'       => 'Accipitridae',
                'genero'        => 'Gyps',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Aves',
                'orden'         => 'Passeriformes',
                'familia'       => 'Corvidae',
                'genero'        => 'Pyrrhocorax',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Aves',
                'orden'         => 'Piciformes',
                'familia'       => 'Picidae',
                'genero'        => 'Dryocopus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Aves',
                'orden'         => 'Passeriformes',
                'familia'       => 'Turdidae',
                'genero'        => 'Turdus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Amphibia',
                'orden'         => 'Caudata',
                'familia'       => 'Salamandridae',
                'genero'        => 'Salamandra',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Amphibia',
                'orden'         => 'Anura',
                'familia'       => 'Ranidae',
                'genero'        => 'Rana',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Amphibia',
                'orden'         => 'Caudata',
                'familia'       => 'Salamandridae',
                'genero'        => 'Triturus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Actinopterygii',
                'orden'         => 'Salmoniformes',
                'familia'       => 'Salmonidae',
                'genero'        => 'Salmo',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Mollusca',
                'clase'         => 'Gastropoda',
                'orden'         => 'Stylommatophora',
                'familia'       => 'Helicidae',
                'genero'        => 'Elona',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Soricomorpha',
                'familia'       => 'Talpidae',
                'genero'        => 'Galemys',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Arthropoda',
                'clase'         => 'Insecta',
                'orden'         => 'Coleoptera',
                'familia'       => 'Lucanidae',
                'genero'        => 'Lucanus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Arthropoda',
                'clase'         => 'Insecta',
                'orden'         => 'Lepidoptera',
                'familia'       => 'Nymphalidae',
                'genero'        => 'Erebia',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Reptilia',
                'orden'         => 'Squamata',
                'familia'       => 'Lacertidae',
                'genero'        => 'Iberolacerta',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Chiroptera',
                'familia'       => 'Rhinolophidae',
                'genero'        => 'Rhinolophus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Mammalia',
                'orden'         => 'Rodentia',
                'familia'       => 'Sciuridae',
                'genero'        => 'Sciurus',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Arthropoda',
                'clase'         => 'Insecta',
                'orden'         => 'Odonata',
                'familia'       => 'Cordulegastridae',
                'genero'        => 'Cordulegaster',
            ],
            [
                'reino'         => 'Animalia',
                'filo_division' => 'Chordata',
                'clase'         => 'Aves',
                'orden'         => 'Passeriformes',
                'familia'       => 'Prunellidae',
                'genero'        => 'Prunella',
            ],
        ];

        $taxonomias = array_merge($taxonomiasFlora, $taxonomiasFauna);

        foreach ($taxonomias as $taxonomia) {
            $existingTaxonomia = Taxonomia::where('genero', $taxonomia['genero'])->first();

            if (! $existingTaxonomia) {
                $slug = Str::slug($taxonomia['genero']);

                $count = Taxonomia::where('slug', 'LIKE', "{$slug}%")->count();
                if ($count > 0) {
                    $slug = "{$slug}-{$count}";
                }

                Taxonomia::create([
                    'reino'         => $taxonomia['reino'],
                    'filo_division' => $taxonomia['filo_division'],
                    'clase'         => $taxonomia['clase'],
                    'orden'         => $taxonomia['orden'],
                    'familia'       => $taxonomia['familia'],
                    'genero'        => $taxonomia['genero'],
                    'slug'          => $slug,
                ]);
            }
        }
    }
}
